# Generated by Django 6.0.5 on 2026-05-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('start_date', models.DateField()),
                ('assignment_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tutor')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.subject')),
            ],
        ),
    ]
