# Generated by Django 6.0.5 on 2026-06-19 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(decimal_places=4, max_digits=19)),
                ('start_date', models.DateField()),
                ('assignment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tutor')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.subject')),
            ],
        ),
    ]
