# Generated by Django 6.0.5 on 2026-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tutor_name', models.CharField(max_length=100)),
                ('tutor_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
