# Generated by Django 6.0.5 on 2026-06-19 04:38

import django.db.models.deletion
import uploads.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_file', models.FileField(upload_to=uploads.models.get_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('QUARANTINED', 'Completed with Quarantined Rows'), ('FAILED', 'System Failure')], default='PENDING', max_length=20)),
                ('file_category', models.CharField(choices=[('LESSON_LOG', 'Lesson Log'), ('INVOICE', 'Invoice'), ('ASSIGNMENT', 'Assignment'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('accepted_rows', models.IntegerField(default=0)),
                ('quarantined_rows', models.IntegerField(default=0)),
                ('system_error_trace', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineRecord',
            fields=[
                ('quarantine_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('raw_payload', models.JSONField(blank=True, help_text='Quarantined row data', null=True)),
                ('reason_code', models.CharField(help_text='e.g., DUPLICATE_RECORD, MALFORMED_DECIMAL', max_length=100)),
                ('error_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_records', to='uploads.upload')),
            ],
            options={
                'ordering': ['row_index'],
            },
        ),
        migrations.CreateModel(
            name='CleanRecord',
            fields=[
                ('clean_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('clean_payload', models.JSONField(help_text='Validated row data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_records', to='uploads.upload')),
            ],
            options={
                'ordering': ['row_index'],
            },
        ),
    ]
