# Generated by Django 6.0.5 on 2026-05-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('total_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_data', models.JSONField()),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('quarantined', 'Quarantined')], max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='uploads.upload')),
            ],
        ),
    ]
