# Generated by Django 6.0.5 on 2026-06-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='status',
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('QUARANTINED', 'Quarantined'), ('FAILED', 'System Failure')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='quarantinerecord',
            name='resolved_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
