# Generated by Django 6.0.5 on 2026-05-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLogs',
            fields=[
                ('log_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('duration_in_hours', models.DecimalField(decimal_places=1, max_digits=19)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=20)),
                ('session_notes', models.TextField()),
                ('fees_charged', models.DecimalField(decimal_places=4, max_digits=19)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
            ],
        ),
    ]
