# Generated by Django 6.0.5 on 2026-05-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('lesson_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonLogs',
            new_name='LessonLog',
        ),
    ]
