# Generated by Django 6.0.5 on 2026-06-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlog',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Aate', 'Late')], max_length=20),
        ),
    ]
