# Generated by Django 6.0.5 on 2026-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_logs', '0004_alter_lessonlog_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlog',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Absent-Mc', 'Absent-Mc')], max_length=20),
        ),
    ]
